### ISSUE TITLE
运行报错listen EACCES 0.0.0.0:80

### ISSUE THREAD

**Issue by dolphinfine** [LiPinghai/node-sorry#2]
安装依赖后运行报错，怎么回事
![image](https://user-images.githubusercontent.com/27426130/38127119-47e9a4f8-3427-11e8-8c41-1c352a86fbe6.png)

**Comment by LiPinghai** [comment]
80端口正在被其他进程占用？

**Comment by dolphinfine** [comment]
我在公司是win7，node v8.x.x版本，在家是win10，也是node v8.x.x版本，报同样的错误，但是我并没有启动其他项目。

**Comment by dolphinfine** [comment]
我换了端口8000，卡在这里不动了
![image](https://user-images.githubusercontent.com/27426130/38160784-78bdad76-34f5-11e8-969c-44075ef5e927.png)

**Comment by LiPinghai** [comment]
这就已经启动了，浏览器访问localhost:8000即可

**Comment by dolphinfine** [comment]
可以了。
